















font_family SFMono Nerd Font
font_size 9
clipboard_control write-clipboard write-primary read-clipboard read-primary
background_opacity 0.7
map ctrl+shift+l next_tab
map ctrl+shift+h previous_tab
window_padding_width 0 0 0 0 
# -----------------------------------------------------------------------------
# STATUS / TAB BAR LAYOUT
# -----------------------------------------------------------------------------
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_margin_width    0.0
tab_bar_margin_height   0.0 0.0

# -----------------------------------------------------------------------------
# HARDCORE HUD COLORS
# -----------------------------------------------------------------------------
# Active tab (The terminal window you are currently working in)
active_tab_foreground   #000000
active_tab_background   #00ff66
active_tab_font_style   bold

# Inactive tabs (Background tasks/idle shells)
inactive_tab_foreground #4e5560
inactive_tab_background #161b22
inactive_tab_font_style normal

# Empty space filling the rest of the bar
tab_bar_background      #0d1117
