#
#
#
#
#
#
#
#
#
#
#
# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '
export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$HOME/.cargo/bin:$PNPM_HOME/bin:$PATH"
eval "$(starship init bash)"
