# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

alias code-oss="code-oss --ozone-platform=wayland"
eval "$(starship init bash)"